apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsback
spec:
  selector:
    app: nodejsback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort
