sonar.projectKey= nodejs-app
sonar.organization=nodejs-app
sonar.projectVersion=2.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://51.222.15.212:9000
sonar.token=squ_6e3c200333ba1354366bad22cbfcde8cf88b6277
sonar.javascript.node.maxspace=4096
sonar.web.http.keepAliveTimeout=120000
sonar.web.http.readTimeout=120000
sonar.exclusions=**/trivy-*.html,**/large_directory/**
sonar.ce.javaOpts=-Xmx8192m -Xms4096m -XX:+HeapDumpOnOutOfMemoryError
sonar.web.javaOpts=-Xmx8192m -Xms4096m -XX:+HeapDumpOnOutOfMemoryError
sonar.search.javaOpts=-Xmx2048m -Xms1024m

